package gr.politeia.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.res.Configuration;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.*;
import android.media.*;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import gr.politeia.core.ElectionEngine;
import gr.politeia.core.Scenario;
import java.math.*;
import java.util.*;

public final class MainActivity extends Activity {
 private static final int BG=0xFFF5F7FA,INK=0xFF152A44,MUTED=0xFF526478,TEAL=0xFF008578,LINE=0xFFE0E6EE;
 private ElectionRepository repository;private JSONObject dataset;private String datasetId="june";
 private boolean greek,percent=true,sounds=true,expanded=false,future=false,resultScreen=false;
 private int editorStep=1; private int pendingScrollY=0;
 private int type=0;private String winner="";private final List<JSONObject> parties=new ArrayList<>();
 private final Map<String,String> values=new LinkedHashMap<>(),transfers=new LinkedHashMap<>();
 private final List<String> tieOrder=new ArrayList<>();
 private final String[] custom={"100","0","20","0","5","1","20"};
 private ElectionEngine.Result result;private LinearLayout root,body;private StepScrollView scroll;private TextView totalLabel,error;
 private final Set<String> selectedParties=new LinkedHashSet<>(),government=new LinkedHashSet<>();
 private JSONObject activePoll;private boolean pollEdited=false;private PollRepository polls;private TextView pollStatus;private boolean refreshing;
 private ToneGenerator tone;private boolean building;
 private View setupStepView,secondStepStartView,inputsStepView;
 private String t(String en,String el){return greek?el:en;}
 private int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle saved){super.onCreate(saved);repository=new ElectionRepository(this);polls=new PollRepository(this);PollUpdateService.schedule(this);greek=getPreferences(0).getBoolean("greek",Locale.getDefault().getLanguage().equals("el"));sounds=getPreferences(0).getBoolean("sounds",true);loadDataset("june");restore();render();}
 @Override protected void onResume(){super.onResume();if(polls!=null&&polls.enabled()&&System.currentTimeMillis()-polls.checked()>PollRepository.INTERVAL)refreshPolls(false);}
 @Override protected void onPause(){save();super.onPause();}
 @Override protected void onDestroy(){if(tone!=null)tone.release();super.onDestroy();}
 private void sound(boolean success){if(!sounds)return;AudioManager am=(AudioManager)getSystemService(AUDIO_SERVICE);if(am.getRingerMode()!=AudioManager.RINGER_MODE_NORMAL)return;try{if(tone==null)tone=new ToneGenerator(AudioManager.STREAM_MUSIC,24);tone.startTone(success?ToneGenerator.TONE_PROP_ACK:ToneGenerator.TONE_PROP_BEEP,success?100:35);}catch(RuntimeException ignored){}}
 private void loadDataset(String id){selectedParties.clear();government.clear();activePoll=null;pollEdited=false;datasetId=id;dataset=repository.get(id);parties.clear();values.clear();transfers.clear();winner="";tieOrder.clear();result=null;resultScreen=false;expanded=false;
  JSONArray a=dataset.optJSONArray("parties");for(int i=0;i<a.length();i++){JSONObject p;try{p=new JSONObject(a.optJSONObject(i).toString());}catch(JSONException e){throw new IllegalStateException(e);}parties.add(p);values.put(p.optString("id"),"0");}}
 private String name(JSONObject p){return p.optString(greek?"el":"en",p.optString("id"));}
 private String title(){if(activePoll!=null)return activePoll.optString("firm")+" · "+activePoll.optString("date")+(pollEdited?t(" · edited scenario"," · τροποποιημένο σενάριο"):t(" · poll scenario"," · δημοσκοπικό σενάριο"));return type==3?t("Custom election","Προσαρμοσμένες εκλογές"):dataset.optString(greek?"el":"en");}
 private String ruleName(){if(type==0)return datasetId.equals("may")?"Ν. 4406/2016":"Ν. 4654/2020";if(type==1)return "Ν. 4255/2014 · Ν. 5083/2024";if(type==2)return future?"Ν. 5314/2026 · Ν. 5321/2026":"Ν. 4804/2021";return t("Your electoral rules","Οι δικοί σας κανόνες");}
 private int seats(){if(type==3){try{return Integer.parseInt(custom[0]);}catch(Exception e){return 0;}}if(type==2&&future){return dataset.optString("kind").equals("region")?ElectionEngine.regionalSeats(dataset.optInt("population"),dataset.optInt("regionId"),true):ElectionEngine.municipalSeats(dataset.optInt("population"),dataset.optInt("units"));}return dataset.optInt("seats");}
 private GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private TextView text(String s,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setFontFeatureSettings("tnum");v.setTypeface(Typeface.create("sans-serif",bold?Typeface.BOLD:Typeface.NORMAL));v.setLineSpacing(dp(3),1);return v;}
 private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
 private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 private void space(LinearLayout l,int height){View v=new View(this);l.addView(v,new LinearLayout.LayoutParams(1,dp(height)));}
 private void weighted(LinearLayout row,View child){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(4),dp(3),dp(4),dp(3));row.addView(child,p);}
 private Button button(String label,String tag,Runnable action,boolean primary){Button b=new Button(this);b.setText(label);b.setTag(tag);b.setAllCaps(false);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(primary?Color.WHITE:INK);b.setPadding(dp(12),dp(9),dp(12),dp(9));b.setMinHeight(dp(50));b.setMinimumHeight(dp(50));b.setStateListAnimator(null);b.setBackground(new RippleDrawable(android.content.res.ColorStateList.valueOf(0x22008578),bg(primary?TEAL:0xFFEAF0F6,12),null));b.setOnClickListener(v->{sound(false);action.run();});return b;}
 private LinearLayout card(LinearLayout parent,String heading){LinearLayout box=column();box.setPadding(dp(20),dp(18),dp(20),dp(20));box.setBackground(bg(Color.WHITE,20));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,dp(8));parent.addView(box,p);if(heading!=null){box.addView(text(heading,19,INK,true));space(box,12);}return box;}
 private void description(LinearLayout p,String s){p.addView(text(s,13,MUTED,false));space(p,10);}
 private void stepButton(LinearLayout parent,String label,String tag,Runnable action,boolean primary){Button b=button(label,tag,action,primary);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(50));p.gravity=Gravity.START;p.setMargins(0,dp(4),0,dp(4));parent.addView(b,p);}
 private void render(){building=true;setupStepView=null;secondStepStartView=null;inputsStepView=null;root=column();root.setBackgroundColor(BG);root.setPadding(dp(16),0,dp(16),0);root.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(dp(16),in.getSystemWindowInsetTop(),dp(16),in.getSystemWindowInsetBottom());return in;});setContentView(root);
  LinearLayout header=row();TextView logo=text(t("politeia","πολιτεία"),26,INK,true);header.addView(logo,new LinearLayout.LayoutParams(0,dp(64),1));logo.setGravity(Gravity.CENTER_VERTICAL);
  Button lang=button(greek?"ΕΛ ▾":"EN ▾","language",()->new AlertDialog.Builder(this).setTitle("Language / Γλώσσα").setItems(new String[]{"English","Ελληνικά"},(d,i)->{greek=i==1;save();render();}).show(),false);header.addView(lang,new LinearLayout.LayoutParams(dp(76),dp(48)));
  Button audio=button(sounds?"♪":"♪ ×","sound",()->{sounds=!sounds;save();render();},false);audio.setContentDescription(t("Sound "+(sounds?"on":"off"),"Ήχος "+(sounds?"ενεργός":"ανενεργός")));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(dp(58),dp(48));ap.setMargins(dp(8),0,0,0);header.addView(audio,ap);Button info=button("ⓘ","sources",this::sources,false);LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(48),dp(48));ip.setMargins(dp(8),0,0,0);header.addView(info,ip);root.addView(header);
  scroll=new StepScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);body=column();body.setPadding(0,dp(12),0,dp(28));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  if(resultScreen&&result!=null)renderResults();else renderEditor();building=false;updateTotal();root.requestApplyInsets();
  final int restoreY=pendingScrollY; pendingScrollY=0;
  scroll.post(()->{updateStepScrollBounds();scroll.scrollTo(0,Math.max(0,restoreY));scroll.clampToBounds();});
 }
 private void renderEditor(){
  body.addView(text(t("FROM VOTES TO REPRESENTATION","ΑΠΟ ΤΗΝ ΨΗΦΟ ΣΤΗΝ ΕΚΠΡΟΣΩΠΗΣΗ"),11,TEAL,true));space(body,8);
  body.addView(text(t("Every vote.\nEvery seat.","Κάθε ψήφος.\nΚάθε έδρα."),34,INK,true));space(body,8);
  description(body,t("Explore how Greece’s votes become seats. Set your election, enter results, and follow the mathematics.","Δείτε πώς οι ψήφοι γίνονται έδρες. Επιλέξτε εκλογές, εισαγάγετε αποτελέσματα και ακολουθήστε τους υπολογισμούς."));
  LinearLayout types=column();String[] names={t("Parliament","Βουλευτικές"),t("European","Ευρωεκλογές"),t("Local","Αυτοδιοικητικές"),t("Custom","Προσαρμοσμένες")};
  for(int j=0;j<2;j++){LinearLayout r=row();for(int k=0;k<2;k++){final int index=j*2+k;weighted(r,button(names[index],"type-"+index,()->switchType(index),type==index));}types.addView(r);}body.addView(types);
  LinearLayout columns=new LinearLayout(this);boolean wide=getResources().getConfiguration().screenWidthDp>=720;columns.setOrientation(wide?LinearLayout.HORIZONTAL:LinearLayout.VERTICAL);columns.setGravity(Gravity.TOP);body.addView(columns);
  LinearLayout left=column(),right=column();if(wide){LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(0,-2,1);l.setMargins(0,0,dp(12),0);columns.addView(left,l);columns.addView(right,new LinearLayout.LayoutParams(0,-2,1.35f));}else{columns.addView(left);columns.addView(right);}
  LinearLayout setup=card(left,t("01  Election setup","01  Ρυθμίσεις εκλογών"));setupStepView=setup;
  if(type!=3){setup.addView(button(title()+"  ▾","dataset",this::chooseDataset,false));space(setup,12);}
  if(type==0){setup.addView(button(t("Latest polls & party lists ▾","Πρόσφατες δημοσκοπήσεις & κόμματα ▾"),"polls",this::choosePoll,false));space(setup,8);pollStatus=text(pollStatusText(),12,MUTED,false);pollStatus.setTag("poll-status");setup.addView(pollStatus);space(setup,6);setup.addView(button(t("Refresh polls now","Ενημέρωση δημοσκοπήσεων τώρα"),"refresh-polls",()->refreshPolls(true),false));CheckBox auto=new CheckBox(this);auto.setText(t("Check for new polls every 6 hours","Έλεγχος νέων δημοσκοπήσεων ανά 6 ώρες"));auto.setTextColor(INK);auto.setChecked(polls.enabled());auto.setOnCheckedChangeListener((v,checked)->polls.setEnabled(checked));setup.addView(auto);description(setup,t("Choose a past election above, or a polling party list. Cached polls work offline; background checks depend on Android and source availability.","Επιλέξτε προηγούμενες εκλογές επάνω ή κόμματα δημοσκόπησης. Η αποθηκευμένη λίστα λειτουργεί εκτός σύνδεσης. Οι έλεγχοι εξαρτώνται από το Android και την πηγή."));if(activePoll!=null)pollNote(setup);}
  LinearLayout metrics=row();LinearLayout seatBox=column();seatBox.addView(text(""+seats(),36,INK,true));seatBox.addView(text(t("total seats","συνολικές έδρες"),12,MUTED,false));weighted(metrics,seatBox);LinearLayout thresholdBox=column();thresholdBox.addView(text(type==3?custom[1]+"%":"3%",28,TEAL,true));thresholdBox.addView(text(t("entry threshold","εκλογικό όριο"),12,MUTED,false));weighted(metrics,thresholdBox);setup.addView(metrics);space(setup,14);
  description(setup,ruleName());
  if(type==0){description(setup,datasetId.equals("may")?t("Simple proportional representation. No bonus.","Απλή αναλογική. Χωρίς μπόνους."):t("20 bonus seats at 25%, then +1 for each 0.5 percentage point. Maximum 50 at 40%.","20 έδρες μπόνους στο 25%, και +1 ανά 0,5 ποσοστιαία μονάδα. Μέγιστο 50 στο 40%."));description(setup,t("National seat entitlement. Constituency exceptions require district-level data.","Εθνική κατανομή εδρών. Εξαιρέσεις εκλογικών περιφερειών απαιτούν τοπικά δεδομένα."));}
  if(type==1)description(setup,t("Greece elects 21 MEPs. Proportional allocation with an integer quota and unused remainders; no bonus.","Η Ελλάδα εκλέγει 21 ευρωβουλευτές. Αναλογική κατανομή με ακέραιο μέτρο και αχρησιμοποίητα υπόλοιπα, χωρίς μπόνους."));
  if(type==2){setup.addView(button(future?t("Current rules · 2026 code ▾","Ισχύοντες κανόνες · Κώδικας 2026 ▾"):t("Historical rules · 2023 ▾","Ιστορικοί κανόνες · 2023 ▾"),"local-law",()->new AlertDialog.Builder(this).setTitle(t("Local election rules","Κανόνες αυτοδιοικητικών εκλογών")).setItems(new String[]{t("Historical · 2023","Ιστορικοί · 2023"),t("Current · Laws 5314/2026, 5321/2026","Ισχύοντες · Ν. 5314/2026, 5321/2026")},(d,i)->{future=i==1;winner="";transfers.clear();tieOrder.clear();render();}).show(),false));space(setup,10);
   description(setup,future?t("First-stage winner: above 42%. Otherwise alternative votes determine the winner. Seats use first preferences. 2023 lists are a scenario starting point; future ballots are not declared.","Νικητής πρώτου σταδίου: πάνω από 42%. Διαφορετικά προσμετρώνται εναλλακτικές ψήφοι. Οι έδρες βασίζονται στις αρχικές ψήφους. Οι συνδυασμοί του 2023 είναι αφετηρία σεναρίου, όχι μελλοντικό ψηφοδέλτιο."):t("Above 43% wins in round one. Otherwise choose the runoff winner. The winner receives rounded 3/5 of seats up to 60%; above 60% all seats are proportional.","Πάνω από 43%: νίκη στον α΄ γύρο. Αλλιώς επιλέξτε νικητή β΄ γύρου. Έως 60% λαμβάνει στρογγυλοποιημένα τα 3/5 των εδρών· πάνω από 60% όλες οι έδρες κατανέμονται αναλογικά."));
   setup.addView(button(winner.isEmpty()?t("Winner: automatic / choose ▾","Νικητής: αυτόματα / επιλογή ▾"):t("Winner: ","Νικητής: ")+partyName(winner),"winner",this::chooseWinner,false));
   if(future){space(setup,8);setup.addView(button(t("Alternative-vote transfers","Μεταφορά εναλλακτικών ψήφων"),"transfers",this::editTransfers,false));}
  }
  if(type==3)customFields(setup);
  space(setup,10);stepButton(setup,t("Next: enter results","Επόμενο: εισαγωγή αποτελεσμάτων"),"next-step",()->{editorStep=2;pendingScrollY=0;render();},true);
  LinearLayout units=card(left,t("Input format","Μορφή εισαγωγής"));secondStepStartView=units;LinearLayout ur=row();weighted(ur,button(t("Percentages %","Ποσοστά %"),"percent",()->changeUnits(true),percent));weighted(ur,button(t("Vote counts","Αριθμός ψήφων"),"votes",()->changeUnits(false),!percent));units.addView(ur);space(units,8);description(units,t("Enter valid votes only. Blank ballots, invalid ballots and abstentions do not enter the denominator.","Μόνο έγκυρες ψήφοι. Λευκά, άκυρα και αποχή δεν συμμετέχουν στον παρονομαστή."));
  if(type!=3){units.addView(button(t("Load historical results","Φόρτωση ιστορικών αποτελεσμάτων"),"example",()->{loadDataset(datasetId);future=false;percent=false;winner=dataset.optString("winner","");for(JSONObject p:parties)values.put(p.optString("id"),""+p.optLong("votes"));tieOrder.clear();transfers.clear();render();},false));space(units,8);description(units,t("Complete published ballot · ","Πλήρες δημοσιευμένο ψηφοδέλτιο · ")+parties.size()+t(" lists. Names reflect the election date; eligibility can change."," συνδυασμοί. Τα ονόματα αφορούν την ημερομηνία των εκλογών· η συμμετοχή μπορεί να αλλάξει."));}
  LinearLayout inputs=card(right,t("02  Enter results","02  Εισαγωγή αποτελεσμάτων"));inputsStepView=inputs;stepButton(inputs,t("← Previous: election setup","← Προηγούμενο: ρυθμίσεις εκλογών"),"previous-step",()->{editorStep=1;pendingScrollY=0;render();},false);space(inputs,8);LinearLayout actions=row();weighted(actions,button(t("Save scenario","Αποθήκευση σεναρίου"),"save",this::saveScenario,false));weighted(actions,button(t("Open scenario","Άνοιγμα σεναρίου"),"open",this::openScenario,false));inputs.addView(actions);space(inputs,10);totalLabel=text("",14,TEAL,true);totalLabel.setTag("input-total");inputs.addView(totalLabel);space(inputs,10);description(inputs,t("Tap a party name for details and coalition settings.","Πατήστε το όνομα για λεπτομέρειες και ρυθμίσεις συνασπισμού."));
  if(parties.isEmpty())description(inputs,t("Add your first party to begin.","Προσθέστε το πρώτο σας κόμμα για να ξεκινήσετε."));
  List<JSONObject> visibleParties=new ArrayList<>();for(JSONObject p:parties)if(!dropdownMode()||selectedParties.contains(p.optString("id")))visibleParties.add(p);
  if(dropdownMode())description(inputs,t("Select parties from the list below. Any unentered share up to 100% becomes rest parties, each assumed below 3% and excluded from seats.","Επιλέξτε κόμματα από τη λίστα. Το υπόλοιπο έως το 100% θεωρείται λοιπά κόμματα, καθένα κάτω από 3%, χωρίς έδρες."));
  int shown=expanded?visibleParties.size():Math.min(visibleParties.size(),8);for(int i=0;i<shown;i++)partyRow(inputs,visibleParties.get(i));
  if(visibleParties.size()>8){space(inputs,8);inputs.addView(button(expanded?t("Show fewer lists","Λιγότεροι συνδυασμοί"):t("Show all "+parties.size()+" lists","Όλοι οι "+parties.size()+" συνδυασμοί"),"expand",()->{expanded=!expanded;render();},false));}
  space(inputs,10);LinearLayout edit=row();weighted(edit,button(t("＋ Add list","＋ Προσθήκη"),"add",()->{if(dropdownMode())chooseParty();else editParty(null);},false));weighted(edit,button(t("Clear values","Μηδενισμός"),"clear",()->{selectedParties.clear();government.clear();if(activePoll!=null)pollEdited=true;for(String id:values.keySet())values.put(id,"0");winner="";tieOrder.clear();transfers.clear();render();},false));inputs.addView(edit);
  if(dropdownMode()){space(inputs,8);inputs.addView(button(t("Create an unlisted party","Δημιουργία άλλου κόμματος"),"create-party",()->editParty(null),false));}
  error=text("",14,0xFFB4233A,true);error.setTag("error");error.setVisibility(View.GONE);inputs.addView(error);space(inputs,14);inputs.addView(button(t("Next: calculate seats","Επόμενο: υπολογισμός εδρών"),"calculate",this::calculate,true));
  lockView(types,editorStep!=1); lockView(setup,editorStep!=1); lockView(units,editorStep!=2); lockView(inputs,editorStep!=2);
 }
 private void lockView(View view,boolean locked){view.setAlpha(locked?0.42f:1f);setEnabledRecursive(view,!locked);}
 private void setEnabledRecursive(View view,boolean enabled){view.setEnabled(enabled);if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++)setEnabledRecursive(group.getChildAt(i),enabled);}}
 private int bodyTop(View view){int[] child=new int[2],base=new int[2];view.getLocationOnScreen(child);body.getLocationOnScreen(base);return child[1]-base[1];}
 private void updateStepScrollBounds(){if(scroll==null||body==null||resultScreen||setupStepView==null||secondStepStartView==null||inputsStepView==null){if(scroll!=null)scroll.setScrollBounds(0,Integer.MAX_VALUE);return;}int top,bottom;if(editorStep==1){top=0;bottom=Math.max(0,bodyTop(setupStepView)+setupStepView.getHeight()-scroll.getHeight()+dp(20));}else{int inputTop=bodyTop(inputsStepView),unitTop=bodyTop(secondStepStartView);top=Math.max(0,Math.min(inputTop,unitTop)-dp(12));bottom=Math.max(top,Math.max(inputTop+inputsStepView.getHeight(),unitTop+secondStepStartView.getHeight())-scroll.getHeight()+dp(20));}scroll.setScrollBounds(top,bottom);}
 private void rerenderPreservingScroll(){pendingScrollY=scroll==null?0:scroll.getScrollY();render();}
 private void partyRow(LinearLayout parent,JSONObject p){LinearLayout r=row();r.setPadding(0,dp(6),0,dp(6));View dot=new View(this);dot.setBackground(bg(Color.parseColor(p.optString("color","#64748B")),5));r.addView(dot,new LinearLayout.LayoutParams(dp(5),dp(34)));
  TextView name=text(name(p),14,INK,true);name.setPadding(dp(10),dp(8),dp(8),dp(8));name.setMinHeight(dp(48));name.setGravity(Gravity.CENTER_VERTICAL);name.setOnClickListener(v->editParty(p));name.setContentDescription(name(p)+t(". Party details",". Στοιχεία συνδυασμού"));r.addView(name,new LinearLayout.LayoutParams(0,-2,1));
  EditText field=field(values.get(p.optString("id")),name(p)+(percent?" %":t(" votes"," ψήφοι")),"value-"+p.optString("id"));field.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);field.setSelectAllOnFocus(true);r.addView(field,new LinearLayout.LayoutParams(dp(112),dp(52)));watch(field,s->{values.put(p.optString("id"),s);if(activePoll!=null)pollEdited=true;government.clear();tieOrder.clear();updateTotal();});if(dropdownMode()){Button remove=button("×","remove-"+p.optString("id"),()->{selectedParties.remove(p.optString("id"));values.put(p.optString("id"),"0");government.clear();tieOrder.clear();if(activePoll!=null)pollEdited=true;render();},false);remove.setContentDescription(t("Remove ","Αφαίρεση ")+name(p));r.addView(remove,new LinearLayout.LayoutParams(dp(48),dp(48)));}parent.addView(r);View line=new View(this);line.setBackgroundColor(LINE);parent.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));}
 private EditText field(String value,String hint,String tag){EditText e=new EditText(this);e.setSingleLine(true);e.setText(value==null?"":value);e.setHint(hint);e.setContentDescription(hint);e.setTag(tag);e.setTextSize(15);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setPadding(dp(12),dp(8),dp(12),dp(8));GradientDrawable d=bg(BG,10);d.setStroke(dp(1),LINE);e.setBackground(d);e.setMinHeight(dp(52));return e;}
 private void watch(EditText e,java.util.function.Consumer<String> c){e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){if(!building)c.accept(s.toString());}public void afterTextChanged(Editable s){}});}
 private BigDecimal number(String s){try{return new BigDecimal(s.trim().replace(',','.'));}catch(Exception e){throw new IllegalArgumentException("NUMBER");}}
 private boolean remainderMode(){return percent&&(type!=3||number(custom[1]).compareTo(new BigDecimal("3"))==0);}
 private boolean dropdownMode(){return percent&&type!=3;}
 private void updateTotal(){if(totalLabel==null)return;try{BigDecimal sum=BigDecimal.ZERO;for(String v:values.values())sum=sum.add(number(v));BigDecimal rest=new BigDecimal("100").subtract(sum);String label=t("Entered: ","Σύνολο: ")+sum.stripTrailingZeros().toPlainString()+(percent?" / 100%":t(" valid votes"," έγκυρες ψήφοι"));if(remainderMode()&&rest.signum()>=0)label+="\n"+t("Rest parties (<3% each): ","Λοιπά κόμματα (<3% έκαστο): ")+rest.stripTrailingZeros().toPlainString()+"%";totalLabel.setText(label);totalLabel.setTextColor(percent&&rest.signum()<0?0xFFB4233A:TEAL);}catch(Exception e){totalLabel.setText(t("Check numeric inputs","Ελέγξτε τους αριθμούς"));}}
 private void chooseParty(){List<JSONObject> available=new ArrayList<>();for(JSONObject p:parties)if(!selectedParties.contains(p.optString("id")))available.add(p);LinearLayout content=column();content.setPadding(dp(16),dp(4),dp(16),0);ListView list=new ListView(this);content.addView(list,new LinearLayout.LayoutParams(-1,dp(420)));ArrayAdapter<JSONObject> adapter=new ArrayAdapter<JSONObject>(this,android.R.layout.simple_list_item_1,available){@Override public View getView(int position,View convert,android.view.ViewGroup parent){LinearLayout line=row();line.setPadding(dp(8),dp(4),dp(8),dp(4));View dot=new View(MainActivity.this);dot.setBackground(bg(Color.parseColor(getItem(position).optString("color","#64748B")),5));line.addView(dot,new LinearLayout.LayoutParams(dp(8),dp(38)));TextView label=text(name(getItem(position)),15,INK,true);label.setGravity(Gravity.CENTER_VERTICAL);label.setPadding(dp(12),0,0,0);line.addView(label,new LinearLayout.LayoutParams(-1,dp(52)));return line;}};list.setAdapter(adapter);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(t("Choose party ▾","Επιλογή κόμματος ▾")).setView(content).setNegativeButton(t("Close","Κλείσιμο"),null).create();dialog.getWindow().setWindowAnimations(0);dialog.setOnShowListener(x->dialog.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND));list.setOnItemClickListener((parent,view,position,id)->{int y=scroll==null?0:scroll.getScrollY();selectedParties.add(available.get(position).optString("id"));expanded=true;pendingScrollY=y;dialog.setOnDismissListener(d->render());dialog.dismiss();});dialog.show();}
 private void switchType(int index){if(index==type)return;type=index;editorStep=1;activePoll=null;government.clear();selectedParties.clear();if(index==3){parties.clear();values.clear();winner="";transfers.clear();tieOrder.clear();resultScreen=false;render();return;}future=index==2;loadDataset(index==0?"june":index==1?"eu":"municipality-9186");if(index==2&&!dataset.optString("kind").equals("municipality")){loadDataset(repository.ofType(2).get(0).optString("id"));}render();}
 private void chooseDataset(){List<JSONObject> all=repository.ofType(type);LinearLayout layout=column();layout.setPadding(dp(20),dp(8),dp(20),0);EditText search=new EditText(this);search.setSingleLine();search.setHint(t("Search municipality or region","Αναζήτηση δήμου ή περιφέρειας"));layout.addView(search);ListView list=new ListView(this);layout.addView(list,new LinearLayout.LayoutParams(-1,dp(360)));List<JSONObject> shown=new ArrayList<>(all);ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1);Runnable refresh=()->{adapter.clear();for(JSONObject e:shown)adapter.add((e.optString("kind").equals("region")?t("Region: ","Περιφέρεια: "):"")+e.optString(greek?"el":"en"));};refresh.run();list.setAdapter(adapter);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(t("Choose election","Επιλογή εκλογών")).setView(layout).setNegativeButton(t("Cancel","Ακύρωση"),null).create();watch(search,s->{shown.clear();for(JSONObject e:all)if((e.optString("en")+e.optString("el")).toLowerCase(Locale.ROOT).contains(s.toLowerCase(Locale.ROOT)))shown.add(e);refresh.run();});list.setOnItemClickListener((a,v,p,id)->{loadDataset(shown.get(p).optString("id"));dialog.dismiss();render();});dialog.show();}
 private String partyName(String id){for(JSONObject p:parties)if(p.optString("id").equals(id))return name(p);return id;}
 private void chooseWinner(){List<String> labels=new ArrayList<>();labels.add(t("Automatic","Αυτόματα"));for(JSONObject p:parties)labels.add(name(p));new AlertDialog.Builder(this).setTitle(t("Declared winner","Δηλωμένος νικητής")).setItems(labels.toArray(new String[0]),(d,i)->{winner=i==0?"":parties.get(i-1).optString("id");transfers.clear();render();}).show();}
 private void changeUnits(boolean target){if(percent==target)return;boolean nonzero=values.values().stream().anyMatch(s->!s.equals("0"));if(nonzero){new AlertDialog.Builder(this).setTitle(t("Change input format?","Αλλαγή μορφής εισαγωγής;")).setMessage(t("This clears the current values. Percentages cannot recover exact vote counts. Saved scenarios are retained.","Οι τρέχουσες τιμές θα μηδενιστούν. Τα ποσοστά δεν δίνουν ακριβείς ψήφους. Τα αποθηκευμένα σενάρια διατηρούνται.")).setPositiveButton(t("Clear & switch","Μηδενισμός & αλλαγή"),(d,w)->{percent=target;for(String id:values.keySet())values.put(id,"0");selectedParties.clear();if(activePoll!=null)pollEdited=true;winner="";transfers.clear();tieOrder.clear();render();}).setNegativeButton(t("Cancel","Ακύρωση"),null).show();}else{percent=target;render();}}
 private void customFields(LinearLayout box){String[] labels={t("Total seats","Συνολικές έδρες"),t("Entry threshold (%)","Εκλογικό όριο (%)"),t("Bonus starts at (%)","Έναρξη μπόνους (%)"),t("Base bonus at start","Αρχικό μπόνους"),t("Percentage points per step","Ποσοστιαίες μονάδες ανά βήμα"),t("Seats gained per step","Έδρες ανά βήμα"),t("Maximum bonus","Μέγιστο μπόνους")};for(int i=0;i<custom.length;i++){box.addView(text(labels[i],12,MUTED,true));space(box,5);final int index=i;EditText e=field(custom[i],labels[i],"custom-"+i);watch(e,s->custom[index]=s);box.addView(e);space(box,10);}description(box,t("Example: start 20%, base 0, step 5, seats per step 1. At 35%, bonus = 3. Set base, seats per step and cap to 0 for simple proportional representation.","Παράδειγμα: έναρξη 20%, αρχικό 0, βήμα 5, έδρες ανά βήμα 1. Στο 35% το μπόνους είναι 3. Ορίστε αρχικό, έδρες ανά βήμα και μέγιστο 0 για απλή αναλογική."));}
 private void editParty(JSONObject original){LinearLayout l=column();l.setPadding(dp(24),dp(8),dp(24),0);EditText en=new EditText(this),el=new EditText(this);en.setHint(t("English name","Αγγλικό όνομα"));el.setHint(t("Greek name","Ελληνικό όνομα"));en.setSingleLine();el.setSingleLine();en.setText(original==null?"":original.optString("en"));el.setText(original==null?"":original.optString("el"));l.addView(en);l.addView(el);l.addView(text(t("Coalition member parties (1 = standalone)","Κόμματα συνασπισμού (1 = αυτοτελές)"),13,MUTED,false));EditText members=field(original==null?"1":""+original.optInt("members",1),"1","members");l.addView(members);if(original!=null)description(l,original.optString(greek?"fullEl":"fullEn"));
  AlertDialog d=new AlertDialog.Builder(this).setTitle(t("Party / electoral list","Κόμμα / συνδυασμός")).setView(l).setPositiveButton(t("Save","Αποθήκευση"),null).setNegativeButton(t("Cancel","Ακύρωση"),null).setNeutralButton(original==null?"":t("Remove","Αφαίρεση"),original==null?null:(x,w)->{parties.remove(original);values.remove(original.optString("id"));tieOrder.clear();render();}).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{try{String a=en.getText().toString().trim(),b=el.getText().toString().trim();if(a.isEmpty()&&b.isEmpty())throw new Exception();if(a.isEmpty())a=b;if(b.isEmpty())b=a;for(JSONObject p:parties)if(p!=original&&(p.optString("en").equalsIgnoreCase(a)||p.optString("el").equalsIgnoreCase(b)))throw new Exception();int count=Integer.parseInt(members.getText().toString());if(count<1||count>100)throw new Exception();JSONObject p=original==null?new JSONObject():original;p.put("en",a).put("el",b).put("members",count);if(original==null){String id="custom-"+UUID.randomUUID();p.put("id",id).put("color",new String[]{"#2979D0","#08A88A","#E56B6F","#9163C7","#D5A631"}[parties.size()%5]);parties.add(p);values.put(id,"0");selectedParties.add(id);}expanded=true;tieOrder.clear();d.dismiss();render();}catch(Exception bad){en.setError(t("Use a unique name and valid member count","Μοναδικό όνομα και έγκυρος αριθμός κομμάτων"));}}));d.show();}
 private void editTransfers(){LinearLayout l=column();l.setPadding(dp(20),dp(8),dp(20),dp(12));description(l,t("Enter transfers to finalists only, from lists eliminated after first preferences. Use the same units as your results. Leave every field blank to use a declared winner.","Μόνο μεταφορές προς φιναλίστ, από αποκλεισμένους συνδυασμούς. Ίδιες μονάδες με τα αποτελέσματα. Κενά πεδία για χρήση δηλωμένου νικητή."));Map<String,EditText> fields=new LinkedHashMap<>();for(JSONObject p:parties){l.addView(text(name(p),13,INK,true));EditText e=field(transfers.getOrDefault(p.optString("id"),""),t("Transferred votes / percentage","Μεταφερόμενες ψήφοι / ποσοστό"),"transfer-"+p.optString("id"));fields.put(p.optString("id"),e);l.addView(e);space(l,8);}ScrollView sv=new ScrollView(this);sv.addView(l);new AlertDialog.Builder(this).setTitle(t("Alternative votes","Εναλλακτικές ψήφοι")).setView(sv).setPositiveButton(t("Apply","Εφαρμογή"),(d,w)->{transfers.clear();for(String id:fields.keySet()){String s=fields.get(id).getText().toString();if(!s.trim().isEmpty())transfers.put(id,s);}winner="";}).setNegativeButton(t("Cancel","Ακύρωση"),null).show();}
 private ElectionEngine.Input input(){ElectionEngine.Rule rule;if(type==3)rule=ElectionEngine.Rule.custom(Integer.parseInt(custom[0]),number(custom[1]).toPlainString(),number(custom[2]).toPlainString(),Integer.parseInt(custom[3]),number(custom[4]).toPlainString(),Integer.parseInt(custom[5]),Integer.parseInt(custom[6]));else if(type==2)rule=future?ElectionEngine.Rule.local2026(seats()):ElectionEngine.Rule.local(seats());else if(type==1)rule=ElectionEngine.Rule.european();else rule=ElectionEngine.Rule.parliament(!datasetId.equals("may"));List<ElectionEngine.Party> rows=new ArrayList<>();for(JSONObject p:parties)rows.add(new ElectionEngine.Party(p.optString("id"),number(values.get(p.optString("id"))),p.optInt("members",1)));ElectionEngine.Input in=new ElectionEngine.Input(rule,rows,percent);Scenario.completePercentages(in);if(!winner.isEmpty())in.winnerId=winner;in.tieOrder=new ArrayList<>(tieOrder);for(String id:transfers.keySet())in.transfers.put(id,number(transfers.get(id)));return in;}
 private void calculate(){try{result=ElectionEngine.calculate(input());government.clear();resultScreen=true;save();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(root.getWindowToken(),0);sound(true);render();}catch(ElectionEngine.TieException tie){error.setText(Explanation.error("TIE",greek));error.setVisibility(View.VISIBLE);String[] labels=tie.parties.stream().map(this::partyName).toArray(String[]::new);new AlertDialog.Builder(this).setTitle(t("Tie: declare lottery outcome","Ισοπαλία: δήλωση κλήρωσης")).setItems(labels,(d,i)->{tieOrder.add(tie.parties.get(i));calculate();}).setNegativeButton(t("Cancel","Ακύρωση"),null).show();}catch(IllegalArgumentException e){error.setText(Explanation.error(e instanceof NumberFormatException?"CONFIG":e.getMessage(),greek));error.setVisibility(View.VISIBLE);error.announceForAccessibility(error.getText());scroll.post(()->{android.graphics.Rect rect=new android.graphics.Rect();error.getDrawingRect(rect);error.requestRectangleOnScreen(rect,false);});}}
 private void renderResults(){body.addView(button(t("← Edit election","← Επεξεργασία εκλογών"),"edit",()->{resultScreen=false;editorStep=2;render();},false));space(body,20);body.addView(text(t("THE SEAT PICTURE","Η ΕΙΚΟΝΑ ΤΩΝ ΕΔΡΩΝ"),11,TEAL,true));space(body,6);body.addView(text(t("Your results, explained.","Τα αποτελέσματα, με εξήγηση."),29,INK,true));description(body,title()+" · "+ruleName());
  LinearLayout summary=card(body,null);TextView total=text(Arrays.stream(result.seats).sum()+t(" seats allocated"," έδρες κατανεμήθηκαν"),28,INK,true);total.setTag("seat-total");summary.addView(total);description(summary,(percent?t("Percentage estimate","Εκτίμηση ποσοστών"):t("Vote-count calculation","Υπολογισμός ψήφων"))+"  ·  "+t("Majority: ","Πλειοψηφία: ")+(seats()/2+1));
  int[] colors=new int[parties.size()];for(int i=0;i<colors.length;i++)colors[i]=Color.parseColor(parties.get(i).optString("color","#64748B"));SeatChart chart=new SeatChart(this,result.seats,colors,t("Seat chamber. Full accessible results below.","Διάγραμμα εδρών. Αναλυτικά αποτελέσματα παρακάτω."));summary.addView(chart,new LinearLayout.LayoutParams(-1,dp(210)));space(summary,18);
  for(int i=0;i<parties.size();i++){if(result.seats[i]==0)continue;final int index=i;LinearLayout r=row();TextView label=text(name(parties.get(i)),15,INK,true);r.addView(label,new LinearLayout.LayoutParams(0,-2,1));TextView number=text(""+result.seats[i],24,INK,true);number.setTag("seats-"+parties.get(i).optString("id"));r.addView(number);summary.addView(r);description(summary,result.percentages[i].setScale(2,RoundingMode.HALF_UP).toPlainString()+"%  ·  "+(result.seats[i]>=seats()/2+1?t("Majority","Πλειοψηφία"):t("Seats: ","Έδρες: ")+result.seats[i]));LinearLayout track=row();track.setBackground(bg(BG,3));View bar=new View(this);bar.setBackground(bg(colors[index],3));track.addView(bar,new LinearLayout.LayoutParams(0,dp(5),result.seats[i]));track.addView(new View(this),new LinearLayout.LayoutParams(0,dp(5),Math.max(0,seats()-result.seats[i])));summary.addView(track);space(summary,15);}
  long zero=Arrays.stream(result.seats).filter(x->x==0).count();if(zero>0)description(summary,zero+t(" lists received no seats. See their thresholds and quotas below."," συνδυασμοί χωρίς έδρα. Δείτε όρια και υπόλοιπα παρακάτω."));
  if(type==0)renderGovernment();if(activePoll!=null){LinearLayout source=card(body,t("Poll source & assumptions","Πηγή δημοσκόπησης & παραδοχές"));pollNote(source);}
  LinearLayout audit=card(body,t("How the seats were allocated","Πώς κατανεμήθηκαν οι έδρες"));audit.getChildAt(0).setTag("explanation");description(audit,t("Every threshold, quota, remainder and bonus is recorded in order.","Κάθε όριο, μέτρο, υπόλοιπο και μπόνους καταγράφεται με τη σειρά."));int k=0;for(ElectionEngine.Step s:result.steps){String p=s.party<0?"":name(parties.get(s.party));TextView v=text((++k)+".  "+Explanation.format(s,greek,p),14,INK,false);v.setTextIsSelectable(true);audit.addView(v);space(audit,12);}
  body.addView(button(t("Sources & methodology","Πηγές & μεθοδολογία"),"sources",this::sources,false));space(body,10);body.addView(button(t("Share calculation","Κοινοποίηση υπολογισμού"),"share",()->{StringBuilder s=new StringBuilder(title()+"\n"+ruleName()+"\n");for(int i=0;i<parties.size();i++)s.append(name(parties.get(i))).append(": ").append(result.seats[i]).append("\n");for(ElectionEngine.Step step:result.steps)s.append(Explanation.format(step,greek,step.party<0?"":name(parties.get(step.party)))).append("\n");if(type!=3)s.append(dataset.optString("source"));Intent send=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,s.toString());startActivity(Intent.createChooser(send,t("Share calculation","Κοινοποίηση υπολογισμού")));},false));
 }
 private String pollStatusText(){if(refreshing)return t("Checking published polls…","Έλεγχος δημοσιευμένων δημοσκοπήσεων…");String checked=polls.checked()==0?t("Bundled snapshot: 10 Sep 2026","Αρχικό στιγμιότυπο: 10 Σεπ 2026"):t("Last successful check: ","Τελευταίος επιτυχής έλεγχος: ")+android.text.format.DateFormat.format("dd MMM yyyy HH:mm",polls.checked());return checked+(polls.error().isEmpty()?"":t(" · Update failed; using saved polls"," · Αποτυχία ενημέρωσης· χρήση αποθηκευμένων"));}
 private void refreshPolls(boolean manual){if(refreshing)return;refreshing=true;if(pollStatus!=null)pollStatus.setText(pollStatusText());new Thread(()->{boolean ok=polls.refresh();runOnUiThread(()->{refreshing=false;if(isDestroyed())return;if(pollStatus!=null)pollStatus.setText(pollStatusText());if(manual)Toast.makeText(this,ok?t("Poll list updated. Your scenario is unchanged.","Η λίστα ενημερώθηκε. Το σενάριό σας διατηρήθηκε."):t("Could not refresh. Saved polls remain available.","Αδυναμία ενημέρωσης. Οι αποθηκευμένες δημοσκοπήσεις παραμένουν διαθέσιμες."),Toast.LENGTH_LONG).show();});},"poll-refresh").start();}
 private void choosePoll(){List<JSONObject> available=polls.all();String[] labels=available.stream().map(p->p.optString("firm")+" · "+p.optString("date")).toArray(String[]::new);new AlertDialog.Builder(this).setTitle(t("Choose an individual poll","Επιλογή δημοσκόπησης")).setItems(labels,(d,i)->{JSONObject poll=available.get(i);new AlertDialog.Builder(this).setTitle(labels[i]).setMessage(t("Source: PolitPro individual-poll table. Date is the fieldwork end date. These are published party shares, not raw undecided responses. For this scenario, Other is assumed to contain only parties below 3%. Polls are estimates, not election results.\n\nLoad its percentages, or use only its party list with your own percentages.","Πηγή: πίνακας μεμονωμένων δημοσκοπήσεων PolitPro. Η ημερομηνία αφορά τη λήξη έρευνας. Δημοσιευμένα ποσοστά κομμάτων, όχι αναποφάσιστοι. Στο σενάριο, τα Λοιπά θεωρούνται κόμματα κάτω από 3%. Οι δημοσκοπήσεις είναι εκτιμήσεις, όχι εκλογικά αποτελέσματα.\n\nΦορτώστε ποσοστά ή μόνο τα κόμματα για δικά σας ποσοστά.")).setPositiveButton(t("Use poll results","Χρήση αποτελεσμάτων"),(x,w)->loadPoll(poll,true)).setNeutralButton(t("Party list only","Μόνο λίστα κομμάτων"),(x,w)->loadPoll(poll,false)).setNegativeButton(t("Cancel","Ακύρωση"),null).show();}).setNegativeButton(t("Close","Κλείσιμο"),null).show();}
 private void loadPoll(JSONObject poll,boolean results){loadDataset("june");type=0;editorStep=2;percent=true;parties.clear();values.clear();try{activePoll=new JSONObject(poll.toString());JSONArray rows=activePoll.getJSONArray("parties");for(int i=0;i<rows.length();i++){JSONObject p=new JSONObject(rows.getJSONObject(i).toString());parties.add(p);String id=p.getString("id");values.put(id,results?p.getString("percentage"):"0");if(results)selectedParties.add(id);}pollEdited=!results;expanded=true;render();save();}catch(JSONException e){throw new IllegalStateException(e);}}
 private void pollNote(LinearLayout box){description(box,activePoll.optString("firm")+" · "+activePoll.optString("date")+t(" (fieldwork end)"," (λήξη έρευνας)")+"\n"+t("Published party shares via PolitPro. Other: ","Δημοσιευμένα ποσοστά μέσω PolitPro. Λοιπά: ")+activePoll.optString("other")+"%. "+t("Other is assumed below 3% per party. Small rounding differences go into the remainder; named party percentages are preserved. Undecided voters are not imported. Polls have sampling uncertainty; this is a seat scenario, not a prediction.","Τα λοιπά θεωρούνται κάτω από 3% ανά κόμμα. Μικρές αποκλίσεις στρογγυλοποίησης προστίθενται στο υπόλοιπο· τα ποσοστά κομμάτων διατηρούνται. Οι αναποφάσιστοι δεν εισάγονται. Υπάρχει δειγματοληπτική αβεβαιότητα· πρόκειται για σενάριο εδρών, όχι πρόβλεψη."));if(pollEdited)description(box,t("Edited scenario — values differ from the published poll.","Τροποποιημένο σενάριο — οι τιμές διαφέρουν από τη δημοσκόπηση."));link(box,t("Open poll source","Άνοιγμα πηγής δημοσκόπησης"),activePoll.optString("source"));if(activePoll.has("primary"))link(box,t("Original GPO / Star publication · 9 Sep 2026","Αρχική δημοσίευση GPO / Star · 9 Σεπ 2026"),activePoll.optString("primary"));}
 private void renderGovernment(){LinearLayout box=card(body,t("Government coalition simulator","Προσομοίωση κυβερνητικής συνεργασίας"));description(box,t("Choose any parties, or a single party. 151 of 300 seats meet the majority target. This tests seat arithmetic; it does not imply political agreement.","Επιλέξτε κόμματα ή ένα μόνο κόμμα. Οι 151 από 300 έδρες καλύπτουν τον στόχο πλειοψηφίας. Ελέγχεται το άθροισμα εδρών, όχι η πολιτική συμφωνία."));TextView score=text("",24,INK,true);score.setTag("government-total");box.addView(score);ProgressBar progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(300);box.addView(progress,new LinearLayout.LayoutParams(-1,dp(12)));TextView status=text("",15,TEAL,true);status.setTag("government-status");box.addView(status);Runnable update=()->{boolean[] chosen=new boolean[parties.size()];for(int i=0;i<chosen.length;i++)chosen[i]=government.contains(parties.get(i).optString("id"));int count=Scenario.coalitionSeats(result.seats,chosen);score.setText(count+" / 300 "+t("seats","έδρες"));progress.setProgress(count);status.setText(Scenario.hasMajority(count)?t("Can form a majority government · ","Δυνατότητα κυβέρνησης πλειοψηφίας · ")+(count-151)+t(" seats above 151"," έδρες πάνω από τις 151"):t("No majority · needs ","Χωρίς πλειοψηφία · χρειάζονται ")+(151-count)+t(" more seats"," ακόμη έδρες"));status.setTextColor(Scenario.hasMajority(count)?TEAL:MUTED);};for(int i=0;i<parties.size();i++){if(result.seats[i]==0)continue;JSONObject party=parties.get(i);String id=party.optString("id");CheckBox check=new CheckBox(this);check.setText(name(party)+" · "+result.seats[i]);check.setTextColor(INK);check.setMinHeight(dp(48));check.setTag("government-"+id);check.setChecked(government.contains(id));check.setOnCheckedChangeListener((v,checked)->{if(checked)government.add(id);else government.remove(id);update.run();save();});box.addView(check);}update.run();}
 private void privacyPolicy(){new AlertDialog.Builder(this).setTitle(t("Privacy policy","Πολιτική απορρήτου")).setMessage(t("Politeia stores language, sound, election inputs and saved scenarios locally on your device. No account, advertising, analytics or crash-reporting SDK is used. Optional poll refresh and source links make network requests to the published source providers; their own privacy policies apply. The app does not intentionally collect or share personal data. Contact the publisher using the support address published with this app.","Η Πολιτεία αποθηκεύει τη γλώσσα, τον ήχο, τις εισαγωγές εκλογών και τα αποθηκευμένα σενάρια τοπικά στη συσκευή. Δεν χρησιμοποιούνται λογαριασμός, διαφημίσεις, analytics ή SDK αναφορών σφαλμάτων. Η προαιρετική ενημέρωση δημοσκοπήσεων και οι σύνδεσμοι πηγών κάνουν δικτυακά αιτήματα προς τους παρόχους των πηγών· ισχύουν οι δικές τους πολιτικές απορρήτου. Η εφαρμογή δεν συλλέγει ούτε κοινοποιεί σκόπιμα προσωπικά δεδομένα. Επικοινωνήστε με τον εκδότη μέσω της διεύθυνσης υποστήριξης που δημοσιεύεται μαζί με την εφαρμογή.")).setPositiveButton(t("Close","Κλείσιμο"),null).show();}
 private void sources(){LinearLayout l=column();l.setPadding(dp(22),dp(12),dp(22),dp(16));description(l,t("Offline ballot snapshots retrieved 10 September 2026. Includes every published list in May/June 2023 parliamentary, 2024 European, and 2023 elections for all 332 municipalities and 13 regions. English local list names are transliterations.","Στιγμιότυπα ψηφοδελτίων: 10 Σεπτεμβρίου 2026. Όλοι οι δημοσιευμένοι συνδυασμοί Μαΐου/Ιουνίου 2023, Ευρωεκλογών 2024 και αυτοδιοικητικών 2023, σε 332 δήμους και 13 περιφέρειες. Αγγλικά ονόματα τοπικών συνδυασμών: μεταγραφή."));description(l,t("National results are seat entitlements under Article 99. Exceptional constituency entitlements under Articles 99(5)/100 need district votes and cannot be derived from nationwide percentages alone. This app does not assign candidates or seats to constituencies.","Εθνικές έδρες βάσει άρθρου 99. Εξαιρέσεις των άρθρων 99(5)/100 απαιτούν ψήφους ανά περιφέρεια και δεν προκύπτουν μόνο από εθνικά ποσοστά. Δεν κατανέμονται υποψήφιοι ή έδρες ανά εκλογική περιφέρεια."));description(l,t("A future ballot is not yet an official party registry. Add or edit lists for scenarios. Lottery decisions are explicit and appear in the explanation. No personal data leaves the app; sound can be switched off.","Το μελλοντικό ψηφοδέλτιο δεν είναι ακόμη επίσημο μητρώο κομμάτων. Προσθέστε ή αλλάξτε συνδυασμούς για σενάρια. Κληρώσεις δηλώνονται ρητά και καταγράφονται. Προσωπικά δεδομένα δεν αποστέλλονται· ο ήχος απενεργοποιείται."));l.addView(button(t("Privacy policy","Πολιτική απορρήτου"),"privacy",this::privacyPolicy,false));space(l,6);
  link(l,t("Official results archive","Επίσημο αρχείο αποτελεσμάτων"),"https://ekloges.ypes.gr/");if(type!=3)link(l,t("Selected dataset (JSON)","Επιλεγμένα δεδομένα (JSON)"),dataset.optString("source"));link(l,"Ν. 4654/2020 · 300", "https://www.hellenicparliament.gr/UserFiles/bcc26661-143b-4f2d-8916-0e0e66ba4c50/eklog-voul-ap-all.pdf");link(l,"Ν. 4255/2014, 5083/2024 · 21","https://www.ypes.gr/wp-content/uploads/2024/05/eggr43270-egk30-20240524.pdf");link(l,"Ν. 4804/2021 · 2023","https://www.ypes.gr/wp-content/uploads/2023/08/eggr65437-egk849-20230803.pdf");link(l,"Ν. 5314/2026 · 33, 56–58, 87","https://www.hellenicparliament.gr/Nomothetiko-Ergo/Anazitisi-Nomothetikou-Ergou?law_id=357e304b-d7d7-410a-8bef-b465011c6f24");ScrollView sv=new ScrollView(this);sv.addView(l);new AlertDialog.Builder(this).setTitle(t("Sources & scope","Πηγές & πεδίο εφαρμογής")).setView(sv).setPositiveButton(t("Close","Κλείσιμο"),null).show();}
 private void link(LinearLayout l,String title,String url){l.addView(button(title,null,()->startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(url))),false));space(l,6);}
 private JSONObject state(){JSONObject s=new JSONObject();try{s.put("selectedParties",new JSONArray(selectedParties)).put("government",new JSONArray(government)).put("activePoll",activePoll).put("pollEdited",pollEdited).put("editorStep",editorStep).put("resultScreen",resultScreen).put("type",type).put("dataset",datasetId).put("percent",percent).put("future",future).put("winner",winner).put("parties",new JSONArray(parties)).put("values",new JSONObject(vSDK Manageralues)).put("custom",new JSONArray(Arrays.asList(custom))).put("transfers",new JSONObject(transfers)).put("tieOrder",new JSONArray(tieOrder));}catch(JSONException e){throw new IllegalStateException(e);}return s;}
 private void apply(JSONObject s){type=s.optInt("type");datasetId=s.optString("dataset","june");dataset=repository.get(datasetId);percent=s.optBoolean("percent",true);future=s.optBoolean("future");winner=s.optString("winner","");editorStep=Math.max(1,Math.min(2,s.optInt("editorStep",1)));parties.clear();values.clear();JSONArray ps=s.optJSONArray("parties");for(int i=0;i<ps.length();i++)parties.add(ps.optJSONObject(i));JSONObject vs=s.optJSONObject("values");for(Iterator<String> it=vs.keys();it.hasNext();){String key=it.next();values.put(key,vs.optString(key));}JSONArray c=s.optJSONArray("custom");for(int i=0;i<custom.length;i++)custom[i]=c.optString(i,custom[i]);transfers.clear();JSONObject tr=s.optJSONObject("transfers");if(tr!=null)for(Iterator<String> it=tr.keys();it.hasNext();){String key=it.next();transfers.put(key,tr.optString(key));}tieOrder.clear();JSONArray ties=s.optJSONArray("tieOrder");if(ties!=null)for(int i=0;i<ties.length();i++)tieOrder.add(ties.optString(i));selectedParties.clear();JSONArray selected=s.optJSONArray("selectedParties");if(selected!=null){for(int i=0;i<selected.length();i++)selectedParties.add(selected.optString(i));}else for(String id:values.keySet())if(number(values.get(id)).signum()>0)selectedParties.add(id);government.clear();JSONArray gov=s.optJSONArray("government");if(gov!=null)for(int i=0;i<gov.length();i++)government.add(gov.optString(i));activePoll=s.optJSONObject("activePoll");pollEdited=s.optBoolean("pollEdited");resultScreen=false;result=null;if(s.optBoolean("resultScreen")){try{result=ElectionEngine.calculate(input());resultScreen=true;}catch(IllegalArgumentException ignored){}}}
 private void save(){getPreferences(0).edit().putBoolean("greek",greek).putBoolean("sounds",sounds).putString("draft",state().toString()).apply();}
 private void restore(){try{String s=getPreferences(0).getString("draft","");if(!s.isEmpty())apply(new JSONObject(s));}catch(Exception ignored){loadDataset("june");}}
 private void saveScenario(){EditText name=new EditText(this);name.setHint(t("Scenario name","Όνομα σεναρίου"));name.setSingleLine();AlertDialog d=new AlertDialog.Builder(this).setTitle(t("Save scenario","Αποθήκευση σεναρίου")).setView(name).setPositiveButton(t("Save","Αποθήκευση"),null).setNegativeButton(t("Cancel","Ακύρωση"),null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String n=name.getText().toString().trim();if(n.isEmpty()){name.setError(t("Enter a name","Εισαγάγετε όνομα"));return;}getSharedPreferences("scenarios",0).edit().putString(n,state().toString()).apply();d.dismiss();Toast.makeText(this,t("Scenario saved","Το σενάριο αποθηκεύτηκε"),Toast.LENGTH_SHORT).show();}));d.show();}
 private void openScenario(){Map<String,?> saved=getSharedPreferences("scenarios",0).getAll();String[] names=saved.keySet().toArray(new String[0]);Arrays.sort(names);if(names.length==0){Toast.makeText(this,t("No saved scenarios yet","Δεν υπάρχουν αποθηκευμένα σενάρια"),Toast.LENGTH_SHORT).show();return;}AlertDialog dialog=new AlertDialog.Builder(this).setTitle(t("Open scenario","Άνοιγμα σεναρίου")).setItems(names,(d,i)->{try{apply(new JSONObject(saved.get(names[i]).toString()));((AlertDialog)d).dismiss();}catch(Exception e){Toast.makeText(this,t("Could not open scenario","Αδυναμία ανοίγματος"),Toast.LENGTH_SHORT).show();}}).setNegativeButton(t("Cancel","Ακύρωση"),null).create();dialog.setOnDismissListener(d->render());dialog.getWindow().setWindowAnimations(0);dialog.setOnShowListener(x->dialog.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND));dialog.show();}
 @Override public void onBackPressed(){if(resultScreen){resultScreen=false;editorStep=2;render();}else super.onBackPressed();}
 private static final class StepScrollView extends ScrollView {
  private int minScroll,maxScroll;
  StepScrollView(Context context){super(context);}
  void setScrollBounds(int min,int max){minScroll=Math.max(0,min);maxScroll=Math.max(minScroll,max);}
  void clampToBounds(){if(getScrollY()<minScroll||getScrollY()>maxScroll)super.scrollTo(getScrollX(),Math.max(minScroll,Math.min(maxScroll,getScrollY())));}
  @Override protected void onScrollChanged(int l,int t,int oldl,int oldt){super.onScrollChanged(l,t,oldl,oldt);int clamped=Math.max(minScroll,Math.min(maxScroll,t));if(clamped!=t)super.scrollTo(l,clamped);}
  @Override public boolean onTouchEvent(android.view.MotionEvent event){boolean handled=super.onTouchEvent(event);if(event.getActionMasked()==MotionEvent.ACTION_MOVE||event.getActionMasked()==MotionEvent.ACTION_UP||event.getActionMasked()==MotionEvent.ACTION_CANCEL)clampToBounds();return handled;}
 }
}
