package gr.politeia.core;
import java.util.*;
import java.math.BigDecimal;
import org.junit.Test;
import static org.junit.Assert.*;
public class CurrentLawTest {
 private ElectionEngine.Input election(String... vs){List<ElectionEngine.Party> p=new ArrayList<>();for(int i=0;i<vs.length;i++)p.add(new ElectionEngine.Party("p"+i,new BigDecimal(vs[i]),1));return new ElectionEngine.Input(ElectionEngine.Rule.local2026(43),p,false);}
 @Test public void secondStageTransfersCanReverseWinner(){ElectionEngine.Input i=election("4100","3500","2400");i.transfers.put("p0",new BigDecimal("100"));i.transfers.put("p1",new BigDecimal("1500"));ElectionEngine.Result r=ElectionEngine.calculate(i);assertEquals(1,r.winner);assertEquals(26,r.seats[1]);}
 @Test public void exactly42NeedsSecondStage(){assertThrows(IllegalArgumentException.class,()->ElectionEngine.calculate(election("4200","3500","2300")));}
 @Test public void above42WinsWithoutTransfers(){assertEquals(0,ElectionEngine.calculate(election("4201","3500","2299")).winner);}
 @Test public void transfersDoNotBecomeSeatVotes(){ElectionEngine.Input i=election("4100","3500","2400");i.transfers.put("p1",new BigDecimal("1000"));int[] a=ElectionEngine.calculate(i).seats;i.transfers.put("p1",new BigDecimal("2000"));assertArrayEquals(a,ElectionEngine.calculate(i).seats);}
 @Test public void cannotTransferMoreThanEliminatedVotes(){ElectionEngine.Input i=election("4100","3500","2400");i.transfers.put("p1",new BigDecimal("2500"));assertThrows(IllegalArgumentException.class,()->ElectionEngine.calculate(i));}
 @Test public void cannotTransferToEliminatedParty(){ElectionEngine.Input i=election("4100","3500","2400");i.transfers.put("p2",new BigDecimal("100"));assertThrows(IllegalArgumentException.class,()->ElectionEngine.calculate(i));}
 @Test public void tiedSecondPlaceIncludesEveryTiedList(){ElectionEngine.Input i=election("4000","3000","3000");i.winnerId="p2";assertEquals(2,ElectionEngine.calculate(i).winner);}
 @Test public void equalSecondStageRequiresLottery(){ElectionEngine.Input i=election("4100","3500","2400");i.transfers.put("p1",new BigDecimal("600"));assertThrows(ElectionEngine.TieException.class,()->ElectionEngine.calculate(i));i.tieOrder.add("p1");assertEquals(1,ElectionEngine.calculate(i).winner);}
 @Test public void currentRegionalSizes(){assertEquals(101,ElectionEngine.regionalSeats(3814064,9,true));assertEquals(85,ElectionEngine.regionalSeats(3814064,9,false));assertEquals(51,ElectionEngine.regionalSeats(327820,12,true));assertEquals(45,ElectionEngine.regionalSeats(327820,12,false));assertEquals(35,ElectionEngine.regionalSeats(300000,1,true));assertEquals(45,ElectionEngine.regionalSeats(300001,1,true));assertEquals(61,ElectionEngine.regionalSeats(800001,1,true));}
 @Test public void municipalPopulationBandsAndUnits(){assertEquals(13,ElectionEngine.municipalSeats(2000,1));assertEquals(15,ElectionEngine.municipalSeats(2001,1));assertEquals(19,ElectionEngine.municipalSeats(5001,1));assertEquals(25,ElectionEngine.municipalSeats(10001,1));assertEquals(29,ElectionEngine.municipalSeats(30001,1));assertEquals(35,ElectionEngine.municipalSeats(50001,1));assertEquals(39,ElectionEngine.municipalSeats(100001,1));assertEquals(43,ElectionEngine.municipalSeats(150001,1));assertEquals(15,ElectionEngine.municipalSeats(2000,5));assertEquals(43,ElectionEngine.municipalSeats(200000,8));}
 @Test public void coalitionAverageCannotStealStandaloneBonus(){List<ElectionEngine.Party> p=Arrays.asList(new ElectionEngine.Party("coalition",new BigDecimal("5000"),2),new ElectionEngine.Party("single",new BigDecimal("3000"),1),new ElectionEngine.Party("other",new BigDecimal("2000"),1));ElectionEngine.Result r=ElectionEngine.calculate(new ElectionEngine.Input(ElectionEngine.Rule.parliament(true),p,false));assertEquals(1,r.winner);assertEquals(30,r.bonus);}
 @Test public void coalitionQualifiesOnAverageStrength(){List<ElectionEngine.Party> p=Arrays.asList(new ElectionEngine.Party("coalition",new BigDecimal("6000"),2),new ElectionEngine.Party("single",new BigDecimal("2501"),1),new ElectionEngine.Party("other",new BigDecimal("1499"),1));ElectionEngine.Result r=ElectionEngine.calculate(new ElectionEngine.Input(ElectionEngine.Rule.parliament(true),p,false));assertEquals(0,r.winner);assertEquals(50,r.bonus);}
 @Test public void explicitRemainderLotteryIsAudited(){ElectionEngine.Input i=new ElectionEngine.Input(ElectionEngine.Rule.custom(3,"0","100",0,"1",0,0),Arrays.asList(new ElectionEngine.Party("a",BigDecimal.ONE,1),new ElectionEngine.Party("b",BigDecimal.ONE,1)),false);i.tieOrder.add("b");assertArrayEquals(new int[]{1,2},ElectionEngine.calculate(i).seats);assertTrue(ElectionEngine.calculate(i).steps.stream().anyMatch(s->s.code.equals("LOTTERY")));}
 @Test public void tiedLeadersBelowBonusStartDoNotNeedLottery(){List<ElectionEngine.Party> p=new ArrayList<>();for(int n=0;n<5;n++)p.add(new ElectionEngine.Party("p"+n,new BigDecimal("20"),1));assertArrayEquals(new int[]{60,60,60,60,60},ElectionEngine.calculate(new ElectionEngine.Input(ElectionEngine.Rule.parliament(true),p,true)).seats);}
}
